spring:
  datasource:
    url: jdbc:mysql://localhost:3306/boards
    username: root
    password: krishnas7
  data:
    mongodb:
      uri: mongodb://hbadmin:hbadmin@localhost:27017/hb-mongo
logging:
  level:
    root: info
    org:
      springframework:
        web: error
    com:
      example:
        kotlinsbdemo: info